# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='author notes', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_author',
            name='authors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_authors.Author'),
        ),
        migrations.AddField(
            model_name='book_author',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_authors.Book'),
        ),
    ]
