# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_auto_20180813_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_author',
            name='authors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book_authors.Author'),
        ),
        migrations.AlterField(
            model_name='book_author',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='book_authors.Book'),
        ),
    ]
