# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-20 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pexam', '0004_auto_20180820_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='wish_id',
            new_name='item_id',
        ),
    ]
